//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handyb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Handyb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct either ANDROID_SDK_HOME or PATH environment variables to include ADB binary..
        /// </summary>
        internal static string ADB_NOT_FOUND_MESSAGE {
            get {
                return ResourceManager.GetString("ADB_NOT_FOUND_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Not Found.
        /// </summary>
        internal static string ADB_NOT_FOUND_TITLE {
            get {
                return ResourceManager.GetString("ADB_NOT_FOUND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon application {
            get {
                object obj = ResourceManager.GetObject("application", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking ADB executable version.
        /// </summary>
        internal static string OUTPUT_CHECKING_VERSION {
            get {
                return ResourceManager.GetString("OUTPUT_CHECKING_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to connect to {0}.
        /// </summary>
        internal static string OUTPUT_CONNECTION_ATTEMPT {
            get {
                return ResourceManager.GetString("OUTPUT_CONNECTION_ATTEMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect with {0}.
        /// </summary>
        internal static string OUTPUT_CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("OUTPUT_CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid IP address.
        /// </summary>
        internal static string OUTPUT_CONNECTION_INVALID_IP {
            get {
                return ResourceManager.GetString("OUTPUT_CONNECTION_INVALID_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected with {0}.
        /// </summary>
        internal static string OUTPUT_CONNECTION_SUCCESS {
            get {
                return ResourceManager.GetString("OUTPUT_CONNECTION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new device has been added.
        /// </summary>
        internal static string OUTPUT_DEVICE_ADDED {
            get {
                return ResourceManager.GetString("OUTPUT_DEVICE_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected or no device is online.
        /// </summary>
        internal static string OUTPUT_DEVICE_OFFLINE {
            get {
                return ResourceManager.GetString("OUTPUT_DEVICE_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected device was removed.
        /// </summary>
        internal static string OUTPUT_DEVICE_REMOVED {
            get {
                return ResourceManager.GetString("OUTPUT_DEVICE_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0} [{1}] - {2}.
        /// </summary>
        internal static string OUTPUT_DEVICE_SELECTED {
            get {
                return ResourceManager.GetString("OUTPUT_DEVICE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please browse to or enter a local path.
        /// </summary>
        internal static string OUTPUT_ENTER_LOCAL {
            get {
                return ResourceManager.GetString("OUTPUT_ENTER_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install {0}.
        /// </summary>
        internal static string OUTPUT_INSTALL_FAILED {
            get {
                return ResourceManager.GetString("OUTPUT_INSTALL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully installed {0}.
        /// </summary>
        internal static string OUTPUT_INSTALL_SUCCESS {
            get {
                return ResourceManager.GetString("OUTPUT_INSTALL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing {0} application(s) to {1} [{2}].
        /// </summary>
        internal static string OUTPUT_INSTALLING_APPS {
            get {
                return ResourceManager.GetString("OUTPUT_INSTALLING_APPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exists.
        /// </summary>
        internal static string OUTPUT_NOT_EXISTS {
            get {
                return ResourceManager.GetString("OUTPUT_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulling {0} to {1} from {2} [{3}].
        /// </summary>
        internal static string OUTPUT_PULLING {
            get {
                return ResourceManager.GetString("OUTPUT_PULLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully pulled {0}.
        /// </summary>
        internal static string OUTPUT_PULLING_FAILED {
            get {
                return ResourceManager.GetString("OUTPUT_PULLING_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to pull {0}.
        /// </summary>
        internal static string OUTPUT_PULLING_SUCCESS {
            get {
                return ResourceManager.GetString("OUTPUT_PULLING_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing {0} to {1} from {2} [{3}].
        /// </summary>
        internal static string OUTPUT_PUSHING {
            get {
                return ResourceManager.GetString("OUTPUT_PUSHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to push {0}.
        /// </summary>
        internal static string OUTPUT_PUSHING_FAILED {
            get {
                return ResourceManager.GetString("OUTPUT_PUSHING_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully pushed {0}.
        /// </summary>
        internal static string OUTPUT_PUSHING_SUCCESS {
            get {
                return ResourceManager.GetString("OUTPUT_PUSHING_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebooting {0} into {1}.
        /// </summary>
        internal static string OUTPUT_REBOOTING {
            get {
                return ResourceManager.GetString("OUTPUT_REBOOTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing list of connected device(s).
        /// </summary>
        internal static string OUTPUT_REFRESHING {
            get {
                return ResourceManager.GetString("OUTPUT_REFRESHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently {0} android device(s) are connected.
        /// </summary>
        internal static string OUTPUT_REFRESHING_RESULT {
            get {
                return ResourceManager.GetString("OUTPUT_REFRESHING_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting running ADB server instance.
        /// </summary>
        internal static string OUTPUT_RESTARTING_ADB {
            get {
                return ResourceManager.GetString("OUTPUT_RESTARTING_ADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taking screenshot from phone.
        /// </summary>
        internal static string OUTPUT_SCREENSHOT {
            get {
                return ResourceManager.GetString("OUTPUT_SCREENSHOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to take screenshot from phone.
        /// </summary>
        internal static string OUTPUT_SCREENSHOT_FAILED {
            get {
                return ResourceManager.GetString("OUTPUT_SCREENSHOT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot saved successfully to {0}.
        /// </summary>
        internal static string OUTPUT_SCREENSHOT_SUCCESS {
            get {
                return ResourceManager.GetString("OUTPUT_SCREENSHOT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting new ADB server instance.
        /// </summary>
        internal static string OUTPUT_STARTING_ADB {
            get {
                return ResourceManager.GetString("OUTPUT_STARTING_ADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping ADB server instance.
        /// </summary>
        internal static string OUTPUT_STOPPING_ADB {
            get {
                return ResourceManager.GetString("OUTPUT_STOPPING_ADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found ADB version {0}.
        /// </summary>
        internal static string OUTPUT_VERSION_FOUND {
            get {
                return ResourceManager.GetString("OUTPUT_VERSION_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find ADB executable version.
        /// </summary>
        internal static string OUTPUT_VERSION_NOT_FOUND {
            get {
                return ResourceManager.GetString("OUTPUT_VERSION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootloader.
        /// </summary>
        internal static string REBOOT_BOOTLOADER {
            get {
                return ResourceManager.GetString("REBOOT_BOOTLOADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string REBOOT_DOWNLOAD {
            get {
                return ResourceManager.GetString("REBOOT_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        internal static string REBOOT_RECOVERY {
            get {
                return ResourceManager.GetString("REBOOT_RECOVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string REBOOT_SYSTEM {
            get {
                return ResourceManager.GetString("REBOOT_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooted: {0}.
        /// </summary>
        internal static string ROOT_STATUS {
            get {
                return ResourceManager.GetString("ROOT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a backround task in progress. Cancel &amp; continue?.
        /// </summary>
        internal static string WORKER_BUSY_MESSAGE {
            get {
                return ResourceManager.GetString("WORKER_BUSY_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Previous Task.
        /// </summary>
        internal static string WORKER_BUSY_TITLE {
            get {
                return ResourceManager.GetString("WORKER_BUSY_TITLE", resourceCulture);
            }
        }
    }
}
